version: "3.7"

services:
  server:
    image: decisionrules/server
    environment:
      - "SHOWCASE=true"
      - "WORKERS_NUMBER=1"
      - "REDIS_URL=redis://host.docker.internal:6379"
      - "MONGO_DB_URI=mongodb://host.docker.internal:27017"
      - "CLIENT_URL=http://localhost:80/#"
      - "LICENSE_KEY=PY5mr_siLCPBg1shUuQv0Q5O~yXXSs.xt5fhtSiCCPD4aDNH"
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - mongoDb
      - redis
    volumes:
      - license:/assets/lic/:rw

  client:
    image: decisionrules/client
    environment:
      - "API_URL=http://localhost:8080"
    ports:
    - "80:80"
    
  mongoDb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  license:
    driver: local